### ISSUE TITLE
Référence ventouse et raccord

### ISSUE THREAD

**Issue by tgv26** [nadarbreicq/Barbatronic#2]
Bonjour, sur les liens indiqués, nous tombons sur plusieurs type possibles, mais sans précision difficile de choisir pour un débutant.
Merci.

**Comment by nadarbreicq** [comment]
Bonjour tgv26,

Effectivement il y a plusieurs ref en fonction des besoins. Concernant les ventouses, j'ai plusieurs ref selon ce que je dois faire. Mais je vais mettre en plus un lien précis vers la ref que j'utilise habituellement. Pareil pour le coupleur. 

Merci de ton message et à bientôt.

**Comment by nadarbreicq** [comment]
Je viens d'ajouter les ref des éléments dans le tableau, car impossible de faire des lien vers une seule référence.

C'est ok pour toi ?

**Comment by tgv26** [comment]
Bonjour, Merci c'est commandé.
Il me manque le radiateur, mais ça doit pouvoir supporter mes tests.
Merci pour tout ton travail.
