### ISSUE TITLE
[BoxGenerator] Présence de distance directe dans Sketch030

### ISSUE THREAD

**Issue by j-wiedemann** [nadarbreicq/Barbatronic#4]
Dans le fichier boxGeneratorV1.3 il reste des contraintes de distance directe dans l'esquisse Sketch030 (Body Bottom, Pad018). Ça provoque la disparitions des languette dans certaine configurations.
Résolu en passant ces contrainte par des contraintes de distance horizontales ou verticales.

```
OS: Ubuntu 20.04.2 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.0224.23964 +3289 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: 2dd87c255154b308a7681c1a7c5740151f340b0a
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: French/France (fr_FR)

```

**Comment by nadarbreicq** [comment]
Hello !
J'ai vu ton précèdent message. En ouvrant l'esquisse pour voir ce qu'il se passait, j'ai détecté l'erreur aussi. Je viens de modifier le fichier et je le push dans quelques minutes.
Je vais vérifier la totalité du fichier ce soir, car j'ai du en laisser passer d'autres... 
Merci pour ton retour !

**Comment by nadarbreicq** [comment]
Corrigé ici : 
https://github.com/nadarbreicq/Barbatronic/commit/0659702e7b2ff61cd64a29d4efb55afe7520beb4
